spring:
  application:
    name: dirk-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
               
server:
  port: 8880

management:
  context-path: /admin
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3721/eureka/
      

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    