spring:
  application:
    name: dirk-hadoop
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/
               
server:
  port: 1234
  
hbase:
  config:
    hbase.zookeeper.quorum: 192.168.1.105
    hbase.zookeeper.property.clientPort: 2181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3721/eureka/
      
hadoop:
  home:
    dir: E:\\study